function allParametricModels = getAllParametricModelNames()
allParametricModels = {'ModelHierarchicalME_MVNORM',...
	'ModelHierarchicalMEUpdated',...
	'ModelHierarchicalME', 'ModelMixedME', 'ModelSeparateME',...
	'ModelHierarchicalLogK', 'ModelMixedLogK', 'ModelSeparateLogK',...
	'ModelHierarchicalHyperboloid', 'ModelMixedHyperboloid', 'ModelSeparateHyperboloid',...
	'ModelHierarchicalExp1', 'ModelMixedExp1', 'ModelSeparateExp1'}; %,...
	%'ModelSeparateExpPower', 'ModelMixedExpPower', 'ModelHierarchicalExpPower'};
warning('temp removed ExpPower models from consideration... they are dealt with elsewhere')
end