function showHDI(samples)

textOrientation = 'vertical';

[HDI] = mcmc.HDIofSamples(samples, 0.95);

hold on

a = axis; top = a(4); k=0.03;
% plot the HDI line
plot(HDI,[top*k top*k],'k-', 'LineWidth',2);
% Add numbers to the CI
lower = sprintf('%.4f',HDI(1));
upper = sprintf('%.4f',HDI(2));
switch textOrientation
	case{'horizontal'}
		t1=text(HDI(1),top*k , lower,...
			'HorizontalAlignment','center',...
			'VerticalAlignment','bottom',...
			'FontSize',14,...
			'BackgroundColor','w');
		t2=text(HDI(2),top*k , upper,...
			'HorizontalAlignment','center',...
			'VerticalAlignment','bottom',...
			'FontSize',14,...
			'BackgroundColor','w');
	case{'vertical'}
		k=0.055;
		t1=text(HDI(1),top*k , lower,...
			'HorizontalAlignment','left',...
			'VerticalAlignment','middle',...
			'FontSize',14,...
			'BackgroundColor','none',...
			'Rotation',90);
		t2=text(HDI(2),top*k , upper,...
			'HorizontalAlignment','left',...
			'VerticalAlignment','middle',...
			'FontSize',14,...
			'BackgroundColor','none',...
			'Rotation',90);
end
% make sure text is on top
uistack(t1,'top');
uistack(t2,'top');
return