function participantFigPlotFuncs = make_participantFigPlotFuncs_LogK()

participantFigPlotFuncs{1} = @(plotdata) mcmc.BivariateDistribution(plotdata.samples.posterior.epsilon,...
	plotdata.samples.posterior.alpha,...
	'xLabel','error rate, $\epsilon$',...
	'ylabel','comparison accuity, $\alpha$',...
	'pointEstimateType', plotdata.pointEstimateType,...
	'plotStyle', 'hist');

participantFigPlotFuncs{2} = @(plotdata) plotPsychometricFunc(plotdata.samples, plotdata.pointEstimateType);

participantFigPlotFuncs{3} = @(plotdata) mcmc.UnivariateDistribution(plotdata.samples.posterior.logk(:),...
	'killYAxis', true,...
	'xLabel', '$\log(k)$',...
	'pointEstimateType', plotdata.pointEstimateType);

participantFigPlotFuncs{4} = @(plotdata) plotDiscountFunction(plotdata);
end