function experimentFigPlotFuncs = make_experimentFigPlotFuncs_LogK()

experimentFigPlotFuncs{1} = @(plotdata) mcmc.BivariateDistribution(plotdata.samples.posterior.epsilon,...
	plotdata.samples.posterior.alpha,...
	'xLabel','error rate, $\epsilon$',...
	'ylabel','comparison accuity, $\alpha$',...
	'pointEstimateType', plotdata.pointEstimateType,...
	'plotStyle', 'hist');

experimentFigPlotFuncs{2} = @(plotdata) plotPsychometricFunc(plotdata.samples, plotdata.pointEstimateType);

experimentFigPlotFuncs{3} = @(plotdata) mcmc.UnivariateDistribution(plotdata.samples.posterior.logk(:),...
	'killYAxis', true,...
	'xLabel', '$\log(k)$',...
	'pointEstimateType', plotdata.pointEstimateType);

experimentFigPlotFuncs{4} = @(plotdata) plotDiscountFunction(plotdata);
end