% demo_WAIC

%% setup
toolbox_path = '~/git-local/delay-discounting-analysis/ddToolbox';
addpath(toolbox_path)
datapath = '~/git-local/delay-discounting-analysis/demo/datasets/kirby';

addpath(toolbox_path)
ddAnalysisSetUp();

mcmc_params = struct('nsamples', 5000,...
		'nchains', 4,...
		'nburnin', 1000);
	
%% Fit multiple models
modelA = ModelSeparateLogK(...
	Data(datapath, 'files', allFilesInFolder(datapath, 'txt')),...
	'savePath', fullfile(pwd,'output','modelA'),...
	'mcmcParams', mcmc_params);

modelB = ModelHierarchicalLogK(...
	Data(datapath, 'files', allFilesInFolder(datapath, 'txt')),...
	'savePath', fullfile(pwd,'output','modelB'),...
	'mcmcParams', mcmc_params);

modelC = ModelHierarchicalExp1(...
	Data(datapath, 'files', allFilesInFolder(datapath, 'txt')),...
	'savePath', fullfile(pwd,'output','modelC'),...
	'mcmcParams', mcmc_params);
	
modelD = ModelHierarchicalHyperboloid(...
	Data(datapath, 'files', allFilesInFolder(datapath, 'txt')),...
	'savePath', fullfile(pwd,'output','modelD'),...
	'mcmcParams', mcmc_params);

%% Examine WAIC stats for models

waic = [modelA.WAIC_stats,...
	modelB.WAIC_stats,...
	modelC.WAIC_stats,...
	modelD.WAIC_stats];

waic_comparison_table = waic.compare()

waic.plot()