function [group1, group2, group1_minus_group2] = demo_group_comparison()
%demo_group_comparison
% This analysis script provides a demonstration of how you can compare two
% different groups. The approach for group comparisons is very simple. 
%   1) Run a model to do parameter estimation for group 1. 
%   2) Run a model to do parameter estimation for group 2.
%   3) Then compare group-level parameters.
%
% THIS IS NOT A REPEATED MEASURES COMPARISON. We are just comparing group 
% level parameter estimates.

% define a cell array of the variables you want to compare
variables_of_interest = {'logk', 'epsilon'};

% Run setup routine
path_of_this_mfile = strrep(which(mfilename),[mfilename '.m'],'');
toolbox_path = fullfile(path_of_this_mfile,'..','ddToolbox');
addpath(toolbox_path)
ddAnalysisSetUp();

%% Define common parameters.
% There's no need to do this as a separate step, but it helps to ensure
% both models are fit with the same parameters
mcmcparams = struct('nsamples', 5000,...
	'nchains', 4,...
	'nburnin', 1000);
pointEstimateType = 'median';
					 
%% Analyse group 1 
datapath1 = fullfile(path_of_this_mfile,'datasets','group_comparison','group1');
group1 = ModelHierarchicalLogK(...
	Data(datapath1, 'files', allFilesInFolder(datapath1, 'txt')),...
	'savePath', fullfile(pwd,'output','group1'),...
	'pointEstimateType', pointEstimateType,...
	'sampler', 'jags',...
	'shouldPlot', 'no',...
	'shouldExportPlots', false,...
	'mcmcParams', mcmcparams);
					 
%% Analyse group 2 
datapath2 = fullfile(path_of_this_mfile,'datasets','group_comparison','group2');
group2 = ModelHierarchicalLogK(...
	Data(datapath2, 'files', allFilesInFolder(datapath2, 'txt')),...
	'savePath', fullfile(pwd,'output','group2'),...
	'pointEstimateType', pointEstimateType,...
	'sampler', 'jags',...
	'shouldPlot', 'no',...
	'shouldExportPlots', false,...
	'mcmcParams', mcmcparams);

%% Compare group level parameter estimates (NOT repeated-measures)
group_level_participant_index = 11; % <--------------------------- FIX ME!!
group1_minus_group2 = group_comparison(...
	group1,...
	group2,...
	variables_of_interest,...
	group_level_participant_index,...
	pointEstimateType);

end