function plotTriPlotWrapper(plotdata)
figure(87)

[posteriorSamples, pVariableNames]	= struct2Matrix(plotdata.samples.posterior);
[priorSamples, ~]		= struct2Matrix(plotdata.samples.prior);

mcmc.TriPlotSamples(posteriorSamples,...
	pVariableNames,...
	'PRIOR', priorSamples,...
	'pointEstimateType', plotdata.pointEstimateType);

myExport('triplot',...
	'saveFolder', plotdata.saveFolder,...
	'prefix', plotdata.IDname,...
	'suffix', plotdata.modelType);
end