function plotPsychometricFunc(mcmcsamples, pointEstimateType)

mcmc.PosteriorPrediction1D(@psychometric_function,...
    'xInterp',linspace(-200,200,200),... % TODO: make this a function of alpha?
    'samples',[mcmcsamples.posterior.epsilon(:) mcmcsamples.posterior.alpha(:)],...
    'ciType','examples',...
    'variableNames', {'$V^B-V^A$', 'P(choose delayed)'},...
	'pointEstimateType',pointEstimateType,...
	'title', 'Psychometric function');

return
