function plotMagnitudeEffect(mcmcsamples, pointEstimateType)

mcmc.PosteriorPrediction1D(@magnitudeEffect,...
    'xInterp',logspace(0,4,50),...
    'samples', [mcmcsamples.posterior.m(:) mcmcsamples.posterior.c(:)],...
    'ciType','examples',...
    'variableNames', {'reward, $\pounds$', '$k$ (days$^{-1}$)'},...
	'pointEstimateType',pointEstimateType,...
	'title', 'Magnitude Effect');

% Extra formatting
set(gca,'XScale','log')
set(gca,'YScale','log')
set(gca,'XTick',logspace(1,6,6))
set(gca,'YTick',logspace(-4,0,5))
return
